title: Huawei Cloud Knowledge Base
description: This blog is a knowledge base created in order to enable faster documentation sharing related to Huawei Cloud.
theme: just-the-docs

url: https://REPO-OWNER-PLACEHOLDER.github.io/REPO-NAME-PLACEHOLDER

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

logo: "https://res-static.hc-cdn.cn/cloudbu-site/intl/en-us/yunying/new-header/logo.png"
favicon_ico: "/assets/images/huawei-logo.png"

color_scheme: huawei

plugins:
  - jekyll-polyglot

languages: ["en", "pt"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public", "sitemap"]
parallel_localization: true

aux_links:
  Contribute: https://github.com/REPO-PLACEHOLDER
