title: Huawei Cloud Knowledge Base
description: This blog is a knowledge base created in order to enable faster documentation sharing related to Huawei Cloud.
theme: just-the-docs

url: https://just-the-docs.github.io

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

logo: "/assets/images/huawei-cloud-logo.jpg"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
